[package]
name = "rssust"
version = "0.0.2"
edition = "2024"

[dependencies]
serde_json = "1.0.150"
anyhow = "1.0.103"
reqwest = { version = "0.13.4", features = ["json", "cookies"] }
scraper = "0.27.0"
rss = "2.1.0"
chrono = "0.4.45"
regex = "1.12.4"
sha1 = "0.10"
md-5 = "0.10"
urlencoding = "2.1"
hex = "0.4"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
tracing = "0.1"
tracing-subscriber = { version = "0.3", default-features = false, features = ["std", "fmt", "ansi", "env-filter"] }
tracing-log = "0.2"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "io-util", "fs", "time", "sync"] }

mdbook = { version = "0.4", optional = true }
bench_scraper = { version = "0.4.1", optional = true }
curl-impersonate-cli = { version = "0.3.1", features = ["download"] }

[features]
default = ["docs", "cookie"]
docs = ["dep:mdbook"]
cookie = ["dep:bench_scraper"]

[profile.release]
lto = "thin"
codegen-units = 1
strip = "symbols"
opt-level = "z"
